# To mount it open prompt, go to DockerFile_TreeDocsService dir and run this command:
# > docker build -f Dockerfile_TreeDocsService -t treedocs_service .


#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.
# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /source
EXPOSE 80
EXPOSE 443

# copy csproj and restore as distinct layers
COPY . ./
WORKDIR /source/Src/01.Presentation/TreeDocs.Service
RUN dotnet build

# copy everything else and build app
#COPY . ./
#WORKDIR /source/Src/01.Presentation/TreeDocs.Service
RUN dotnet publish -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "TreeDocs.Service.dll"]
