version: '3.4'

services:
  treenotes_service:
    image: ${DOCKER_REGISTRY-}treenotesservice
    build:
      context: .
      dockerfile: Dockerfile_TreeNotesService
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5100
    depends_on:
      - redis
      - mongodb
      - seq
    ports:
      - "5100:5100"
    restart: unless-stopped    


  treenotes_ui:
    image: ${DOCKER_REGISTRY-}treenotesui
    build:
      context: .
      dockerfile: Dockerfile_TreeNotesUI
      args:
        - VITE_TREE_DOCS_SERVICE_URL=http://localhost:5100
    environment:
      - VITE_TREE_DOCS_SERVICE_URL=http://localhost:5100
    depends_on:
      - treenotes_service
    ports:
      - "5200:80"
    restart: unless-stopped


  redis:
    image: "redis"
    ports:
      - "63800:6379"
    restart: unless-stopped    


  mongodb:
    image: "mongo"
    ports:
      - "27018:27017"
    restart: unless-stopped    

  seq:
    image: "datalust/seq"
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5342:80"
    restart: unless-stopped
