# To mount it open prompt, go to DockerFile_TreeDocsClientApp dir and run this command:
# > docker build -f Dockerfile_TreeDocsClientApp -t treedocs_clientapp .

#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.
# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /source
EXPOSE 80
EXPOSE 443

# copy csproj and restore as distinct layers
COPY . ./
WORKDIR /source/Src/01.Presentation/TreeDocs.ClientApp
RUN dotnet build

# copy everything else and build app
RUN dotnet publish -c release -o /app --no-restore

# final stage/image
FROM nginx AS final
WORKDIR /app

# copy the application to the static nginx file server
COPY --from=build ["/app/wwwroot", "/usr/share/nginx/html"]

# copy the customized Nginx configuration file in order to work better under a blazor app
COPY --from=build ["/source/Src/01.Presentation/TreeDocs.ClientApp/Nginx", "/etc/nginx/templates"]
