services:
  treenotes_service:
    image: ${DOCKER_REGISTRY-}treenotesservice
    build:
      dockerfile: Dockerfile_TreeNotesService
    environment:
      - TreeNotesDb__ConnectionString=mongodb://admin:12345678a@mongodb:27017
      - TreeNotesDb__DatabaseName=NoterDb
      - redis__configuration=redis:6379
      # optionals:
      #- TreeNotesAuthenticationDb__ConnectionString=mongodb://admin:12345678a@mongodb:27017
      #- AuditDatabase__ConnectionString=mongodb://admin:12345678a@mongodb:27017
      - TreeNotesAuthenticationDb__DatabaseName=Users
      - AuditDatabase__DatabaseName=AuditTrail

    depends_on:
      - redis
      - mongodb
      - seq
    ports:
      - "5100:80"
    restart: unless-stopped    


  treenotes_ui:
    image: ${DOCKER_REGISTRY-}treenotesui
    build:
      dockerfile: Dockerfile_TreeNotesUI
    environment: 
      - TREE_NOTES_SERVICE_URL=http://localhost:5100
    depends_on:
       - treenotes_service
    ports:
      - "5200:80"
    restart: unless-stopped


  redis:
    image: "redis"
    ports:
      - "63800:6379"
    restart: unless-stopped    


  mongodb:
    image: "mongo"
    ports:
      - "27018:27017"
    environment:
      - ACCEPT_EULA=Y
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=12345678a
    restart: unless-stopped    

  seq:
    image: "datalust/seq:5.1.3364"
    ports:
      - "5342:80"
    environment:
      - ACCEPT_EULA=Y
    restart: unless-stopped
