//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeNotes.Domain.RequestResponses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DomainResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TreeNotes.Domain.RequestResponses.DomainResources", typeof(DomainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Pasta definida não existe.
        /// </summary>
        internal static string ErrFolderNotFound {
            get {
                return ResourceManager.GetString("ErrFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este elemento já existe sob esta pasta.
        /// </summary>
        internal static string ErrNodeAlreadyExists {
            get {
                return ResourceManager.GetString("ErrNodeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId deve ser preenchido..
        /// </summary>
        internal static string ErrUserIdRequired {
            get {
                return ResourceManager.GetString("ErrUserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome do elemento deve ter no mínimo {0} caracteres..
        /// </summary>
        internal static string ErrUserNameMaxLen {
            get {
                return ResourceManager.GetString("ErrUserNameMaxLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome do elemento deve ter no máximo {0} caracteres..
        /// </summary>
        internal static string ErrUserNameMinLen {
            get {
                return ResourceManager.GetString("ErrUserNameMinLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parâmetro NodeId deve ser preenchido.
        /// </summary>
        internal static string ErrUserNodeIdRequired {
            get {
                return ResourceManager.GetString("ErrUserNodeIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Elemento &apos;{0}&apos; foi criado com sucesso..
        /// </summary>
        internal static string MsgNodeCreationSuccess {
            get {
                return ResourceManager.GetString("MsgNodeCreationSuccess", resourceCulture);
            }
        }
    }
}
