//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auth.Domain.RequestsResponses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Auth.Domain.RequestsResponses.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old password is invalid.
        /// </summary>
        internal static string ErrInvalidOldPassword {
            get {
                return ResourceManager.GetString("ErrInvalidOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        internal static string ErrInvalidPassword {
            get {
                return ResourceManager.GetString("ErrInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Request.
        /// </summary>
        internal static string ErrInvalidRequest {
            get {
                return ResourceManager.GetString("ErrInvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to create user because there are validation errors.
        /// </summary>
        internal static string ErrInvalidUserCreationRequest {
            get {
                return ResourceManager.GetString("ErrInvalidUserCreationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user Email is invalid.
        /// </summary>
        internal static string ErrInvalidUserEmail {
            get {
                return ResourceManager.GetString("ErrInvalidUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password cannot have more than {0} characters..
        /// </summary>
        internal static string ErrMaxPasswordLen {
            get {
                return ResourceManager.GetString("ErrMaxPasswordLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User Name cannot have more than {0} characters..
        /// </summary>
        internal static string ErrMaxUserLen {
            get {
                return ResourceManager.GetString("ErrMaxUserLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password must have more then {0} characters..
        /// </summary>
        internal static string ErrMinPasswordLen {
            get {
                return ResourceManager.GetString("ErrMinPasswordLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User Name must have more then {0} characters..
        /// </summary>
        internal static string ErrMinUserLen {
            get {
                return ResourceManager.GetString("ErrMinUserLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorized operation &apos;{0}&apos;..
        /// </summary>
        internal static string ErrNotAuthorizedOperation {
            get {
                return ResourceManager.GetString("ErrNotAuthorizedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old and New password must be different.
        /// </summary>
        internal static string ErrOldAndNewPasswordCannotBeEqual {
            get {
                return ResourceManager.GetString("ErrOldAndNewPasswordCannotBeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Administrators can register other Administrators.
        /// </summary>
        internal static string ErrOnlyAdminCanCreateAdmins {
            get {
                return ResourceManager.GetString("ErrOnlyAdminCanCreateAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This parameters is required..
        /// </summary>
        internal static string ErrParameterRequired {
            get {
                return ResourceManager.GetString("ErrParameterRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to update user because there are validation errors.
        /// </summary>
        internal static string ErrUpdatingUser {
            get {
                return ResourceManager.GetString("ErrUpdatingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already in use by another user.
        /// </summary>
        internal static string ErrUserAlreadyExists {
            get {
                return ResourceManager.GetString("ErrUserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either UserId or UserPassword must be filled.
        /// </summary>
        internal static string ErrUserIdOrUserEmailRequired {
            get {
                return ResourceManager.GetString("ErrUserIdOrUserEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId is required.
        /// </summary>
        internal static string ErrUserIdRequired {
            get {
                return ResourceManager.GetString("ErrUserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is required.
        /// </summary>
        internal static string ErrUserNameRequired {
            get {
                return ResourceManager.GetString("ErrUserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; not found.
        /// </summary>
        internal static string ErrUserNotFound {
            get {
                return ResourceManager.GetString("ErrUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User password is required.
        /// </summary>
        internal static string ErrUserPasswordRequired {
            get {
                return ResourceManager.GetString("ErrUserPasswordRequired", resourceCulture);
            }
        }
    }
}
