//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeNotes.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DomainResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TreeNotes.Domain.DomainResources", typeof(DomainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to create a child in another user element.
        /// </summary>
        internal static string ErrCannotCreateNodeInAnotherUserNode {
            get {
                return ResourceManager.GetString("ErrCannotCreateNodeInAnotherUserNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node cannot be moved to a descendent node..
        /// </summary>
        internal static string ErrCannotMoveNodeToDescendent {
            get {
                return ResourceManager.GetString("ErrCannotMoveNodeToDescendent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent element was not found.
        /// </summary>
        internal static string ErrFolderNotFound {
            get {
                return ResourceManager.GetString("ErrFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This element already exists under this parent element.
        /// </summary>
        internal static string ErrNodeAlreadyExists {
            get {
                return ResourceManager.GetString("ErrNodeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element cannot be its own father.
        /// </summary>
        internal static string ErrNodeCannotBeItsOwnParent {
            get {
                return ResourceManager.GetString("ErrNodeCannotBeItsOwnParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element must have a parent.
        /// </summary>
        internal static string ErrNodeMustHaveParent {
            get {
                return ResourceManager.GetString("ErrNodeMustHaveParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element not found.
        /// </summary>
        internal static string ErrNodeNotFound {
            get {
                return ResourceManager.GetString("ErrNodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while removing the note.
        /// </summary>
        internal static string ErrNoteCouldNotBeRemoved {
            get {
                return ResourceManager.GetString("ErrNoteCouldNotBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The was an error while removing the note because some child notes could not be removed.
        /// </summary>
        internal static string ErrSomeChildrenCouldNotBeRemoved {
            get {
                return ResourceManager.GetString("ErrSomeChildrenCouldNotBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The note name must have at least {0} characters.
        /// </summary>
        internal static string ErrUserNameMaxLen {
            get {
                return ResourceManager.GetString("ErrUserNameMaxLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The note name must have a maximum of {0} characters.
        /// </summary>
        internal static string ErrUserNameMinLen {
            get {
                return ResourceManager.GetString("ErrUserNameMinLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The note &apos;{0}&apos; was created successfully.
        /// </summary>
        internal static string MsgNodeCreationSuccess {
            get {
                return ResourceManager.GetString("MsgNodeCreationSuccess", resourceCulture);
            }
        }
    }
}
